//
//  Header.h
//  CYPA
//
//  Created by 黄冬冬 on 16/1/18.
//  Copyright © 2016年 HDD. All rights reserved.
//

#ifndef Header_h
#define Header_h

#define SIZE_SCALE_IPHONE6(x)   (x * ([UIScreen mainScreen].bounds.size.width / 375))
#define placeholdPicture @"placeholder"

#endif /* Header_h */

#define APPID @"wx5018f99ee43d6442"
#define APPSECRET @"d4624c36b6795d1d99dcf0547af5443d"
#define BASE_URL @"https://api.weixin.qq.com"
#define SERVER_URL [NSString stringWithFormat:@"%@/rmb/third_pay/weixin", BaseURL] 
//@"http://www.cypalife.com/Plus/WeiXin/"
#define NOTIFY_URL [NSString stringWithFormat:@"%@/rmb/third_pay/weixin", BaseURL]
#define PartnerId @"1288580901"

#define Partner_Sign_Key @"sczJpiMw6V3YO1lPOSL9VsrueXwrIEiK"

#define IOS_CELLULAR    @"pdp_ip0"
#define IOS_WIFI        @"en0"
#define IP_ADDR_IPv4    @"ipv4"
#define IP_ADDR_IPv6    @"ipv6"


#define AlipayPartner    @"2088311095912814"
#define AlipaySeller     @"cypacypa@163.com"
#define AlipayScheme    @"cypapartment"
#define AlipayPrivateKey    @"MIICdgIBADANBgkqhkiG9w0BAQEFAASCAmAwggJcAgEAAoGBAN35+ZhIvN/PBF8Ad1yQ6OkBUwbVD0d5rD5YD5HkKtuh1cd+Nrrsp6L79EeVvNcarezaLOlyB6b0drI+DGg6mVzK5XzlZaxcIIo1KzLobKdYGZORWduBkIAdn52kvDlMIIWOJw7L0Dekqd9TMK7GPIEbrmH/D3u5hrCqYK6AULu/AgMBAAECgYAYPNdYHXkiJwSfKvndjaUg7BgYwuLsNwjrtcndcECNwtoI8msfdf/H+CLwPhVkl3EuT5Rf2Sekv0TGqafJKbzdBNExgmrUfghKUZyIXlxbXcFoF9boo6AJknFQ3guT+oiTxy8P/M3KOveCW9mbsUCpmY7LvoWXF+0nJDbfMisPwQJBAP3YoQgtx+LVyPiqAsidbAfgxJXa0hd97bphZHkY93xNIrTO2v9/G8htMh2fbV0sS7VS5XWVIU1ejBS1ndNT+EcCQQDf3B9rcb4X0K5HkG2yB0OJk3c4NHdddLF+eKGnZoL9Bj7wtfXXjtFsRe4ytOcoOlHwkxrBPOgtVBtgpoHT+NTJAkA5GMHXyhxcvENxEyR/JVGIUBlHr6lz2UJgmslzp5b7IYp96s09jMSeB1mvag26WF1LErNECGAuO+b8PYGbaBa/AkEAyj+Lu3z163pEGq/oC3H4mLE8gvET7sFhIwxFsIIzUfp0nvEmfWuw1YuQmwtJ1NRr91hQUcl/UoSsf3Ov1Bz50QJAe6CH+X4rmCLKa+NaeMqn4Xleqvj3g1tnqfu3ZayWbClUsDzwn49jeD4GPfVamL6P/ggItPpIZHfX/hxKqQdP7A=="

#import "RootTabBarController.h"
#import "IndexViewController.h"
#import "IntelligenceViewController.h"
#import "KnockCollectionViewCell.h"
#import "LinkViewController.h"
#import "UIColor+hexColor.h"
#import "NeighbourViewController.h"
#import "Masonry.h"
#import "BasePersonViewController.h"
#import "BaseViewController.h"
#import "BaseTitleViewController.h"
#import "PersonShowViewController.h"
#import "AboutPersonViewController.h"
#import "OrderView.h"
#import "AFNetworking.h"
#import "AFNetworkReachabilityManager.h"

#import "Reachability.h"

#import "ChooseLoginViewController.h"
#import "LoginViewController.h"
#import "VisitorLoginViewController.h"
#import "XPCoinViewController.h"
#import "XPButlerViewController.h"
#import "XPLinkViewController.h"
#import "XPRentViewController.h"
#import "UIImageView+WebCache.h"
#import "CleanViewController.h"
#import "ServiceViewController.h"
#import "ComplainViewController.h"
#import "GXNetWorkManager.h"
#import "ServiceHistoryViewController.h"
#import "DatailViewController.h"
#import "EvaluateViewController.h"
#import "BusinessJoinViewController.h"
#import "CleanViewController.h"
#import "ServiceViewController.h"
#import "ComplainViewController.h"
#import "GXNetWorkManager.h"
#import "PayHistoryViewController.h"
#import "VoucherViewController.h"
#import "KindOfVoucherViewController.h"
#import "MoreNeighbourViewController.h"
#import "MoreShowViewController.h"
#import "ShowDetailViewController.h"
#import "PublishViewController.h"
#import "TalkViewController.h"
#import "MoreTrystViewController.h"
#import "PublishActivityViewController.h"
#import "ActivityDetailViewController.h"
#import "PromptViewController.h"
#import "FriendListViewController.h"
#import "PersonSettingViewController.h"
#import "KindOfPayViewController.h"
#import "PayDetailViewController.h"
#import "ServiceDetailViewController.h"
#import "BussinessWebViewController.h"
#import "MyNewsViewController.h"
#import "MyTrystViewController.h"
#import "MyDynamicViewController.h"
#import "MyContractViewController.h"
#import "MyBillViewController.h"
#import "AnnouncementViewController.h"
#import "MyShowViewController.h"
#import "MyKnockViewController.h"
#import "PersonCenterViewController.h"
#import "OutletsViewController.h"
#import "OutLetsPayViewController.h"
#import "PayCoinViewController.h"
#import "MyOrderViewController.h"
#import "PassWordViewController.h"
#import "TestPassWordViewController.h"
#import "GetCodeViewController.h"
#import "SettingChoiseViewController.h"
#import "ForgetPassWordViewController.h"
#import "ResertPassWordViewController.h"
#import "PassWordChoisceViewController.h"
#import "RetrieveViewController.h"
#import "CoinPassWordSettingViewController.h"
#import "CoinOldPassWordViewController.h"
#import "CoinNewPassWordViewController.h"
#import "PictureViewController.h"
#import "LinkWebViewController.h"
#import "AboutUsViewController.h"
#import "CheckPasswordViewController.h"

//cell
#import "LockTitleTableViewCell.h"
#import "LockTableViewCell.h"
#import "ConditionTitleTableViewCell.h"
#import "ConditionTableViewCell.h"
#import "LockHistoryViewController.h"
#import "LockHistoryTableViewCell.h"
#import "LockRecordTableViewCell.h"
#import "BusinessTableViewCell.h"
#import "KindTableViewCell.h"
#import "KindCollectionViewCell.h"
#import "DatailTableViewCell.h"
#import "ServiceHistoryTableViewCell.h"
#import "PayHistoryTableViewCell.h"
#import "NeighbourTableViewCell.h"
#import "ShowCollectionViewCell.h"
#import "TrystCollectionViewCell.h"
#import "CitizenTableViewCell.h"
#import "PersonShowTableViewCell.h"
#import "MyTalkTableViewCell.h"
#import "OthersTableViewCell.h"
#import "MoreTrystTableViewCell.h"
#import "FriendTableViewCell.h"
#import "kindOfPayTableViewCell.h"
#import "MyNewsTableViewCell.h"
#import "PayTableViewCell.h"
#import "InvateTrystTableViewCell.h"
#import "FunctionTableViewCell.h"
#import "PersonDetailTableViewCell.h"
#import "OutletsCollectionViewCell.h"
#import "OutletsProductTableViewCell.h"
#import "MyOrderTableViewCell.h"
#import "SwitchTableViewCell.h"


//Model
#import "XPCitizen.h"
#import "XPCertificate.h"
#import "XPBaseModel.h"
#import "XPServiceModel.h"
#import "UPerson.h"
#import "TrystModel.h"
#import "TalkModel.h"
#import "CheckModel.h"
#import "BussinessModel.h"
#import "FriendModel.h"
#import "FriendTableViewCell.h"
#import "MyKnockTableViewCell.h"
#import "NewsModel.h"
#import "ContractModel.h"
#import "ProductModel.h"
#import "OrderModel.h"


#import "StarView.h"
#import "UITextField+UIDatePicker.h"
#import "UITextField+DatePickerModelDate.h"
#import "BottomButton.h"
#import "HeadButton.h"
#import "TopLabel.h"
#import "VistorView.h"
#import "NetWorkView.h"
#import "UIButton+WebCache.h"
#import "UIImageView+WebCache.h"
#import "ApiStoreSDK.h"
#import "JPUSHService.h"
#import "MBProgressHUD+Add.h"
#import "UIImage+ChangeColor.h"
